import { Geist, Geist_Mono, Syne, Oswald, Montserrat} from "next/font/google";
import "./globals.css";

import NavBarMain from "@/components/Navbar/NavbarMain";
import FooterMain from "@/components/Footer/FooterMain";
import ClientNavbar from "@/components/Navbar/ClientNavBar";

const montserrat = Montserrat ({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const syne = Syne ({
  variable: "--font-syne",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-Oswald",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${syne.variable} ${oswald.variable} antialiased`}
      >
        <ClientNavbar />
          {children}
        <FooterMain/>
      </body>
    </html>
  );
}